/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.hotelmanage.ui.panel;

/**
 *
 * @author hoang
 */
public class RoomPopup extends javax.swing.JPanel {

    /**
     * Creates new form RoomPopup
     */
    public RoomPopup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblService = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbPhoneNumCustomer = new javax.swing.JLabel();
        lbNameCustomer = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbRoomNum = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbTypeOfRoom = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbnNumberOfPeople = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbTimeCheckin = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        tblService.setFont(new java.awt.Font("Barlow Condensed", 0, 12)); // NOI18N
        tblService.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã dịch vụ", "Loại dịch vụ", "Tên dịch vụ", "Giờ đặt dịch vụ", "Trạng thái"
            }
        ));
        jScrollPane2.setViewportView(tblService);

        jLabel7.setFont(new java.awt.Font("Barlow Condensed", 0, 14)); // NOI18N
        jLabel7.setText("Ngày/Giờ nhận phòng:");

        jLabel8.setFont(new java.awt.Font("Barlow Condensed", 0, 14)); // NOI18N
        jLabel8.setText("Thời gian sử dụng:");

        jLabel9.setFont(new java.awt.Font("Barlow Condensed", 0, 14)); // NOI18N
        jLabel9.setText("Dịch vụ đã gọi:");

        lbPhoneNumCustomer.setFont(new java.awt.Font("Barlow Condensed", 0, 14)); // NOI18N
        lbPhoneNumCustomer.setText("...");

        lbNameCustomer.setFont(new java.awt.Font("Barlow Condensed", 0, 14)); // NOI18N
        lbNameCustomer.setText("...");

        jLabel1.setFont(new java.awt.Font("Barlow Condensed", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thông tin chi tiết");

        lbRoomNum.setFont(new java.awt.Font("Barlow Condensed", 0, 14)); // NOI18N
        lbRoomNum.setText("...");

        jLabel2.setFont(new java.awt.Font("Barlow Condensed", 0, 14)); // NOI18N
        jLabel2.setText("Người nhận phòng:");

        lbTypeOfRoom.setFont(new java.awt.Font("Barlow Condensed", 0, 14)); // NOI18N
        lbTypeOfRoom.setText("...");

        jLabel3.setFont(new java.awt.Font("Barlow Condensed", 0, 14)); // NOI18N
        jLabel3.setText("Số điện thoại:");

        lbnNumberOfPeople.setFont(new java.awt.Font("Barlow Condensed", 0, 14)); // NOI18N
        lbnNumberOfPeople.setText("...");

        jLabel4.setFont(new java.awt.Font("Barlow Condensed", 0, 14)); // NOI18N
        jLabel4.setText("Số phòng:");

        lbTimeCheckin.setFont(new java.awt.Font("Barlow Condensed", 0, 14)); // NOI18N
        lbTimeCheckin.setText("...");

        jLabel5.setFont(new java.awt.Font("Barlow Condensed", 0, 14)); // NOI18N
        jLabel5.setText("Loại phòng:");

        jLabel17.setFont(new java.awt.Font("Barlow Condensed", 0, 14)); // NOI18N
        jLabel17.setText("...");

        jLabel6.setFont(new java.awt.Font("Barlow Condensed", 0, 14)); // NOI18N
        jLabel6.setText("Số lượng người:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbNameCustomer))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbPhoneNumCustomer))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTypeOfRoom))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbRoomNum))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbnNumberOfPeople))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTimeCheckin))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17))
                    .addComponent(jLabel9))
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbNameCustomer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbPhoneNumCustomer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lbRoomNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lbTypeOfRoom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lbnNumberOfPeople))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lbTimeCheckin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbNameCustomer;
    private javax.swing.JLabel lbPhoneNumCustomer;
    private javax.swing.JLabel lbRoomNum;
    private javax.swing.JLabel lbTimeCheckin;
    private javax.swing.JLabel lbTypeOfRoom;
    private javax.swing.JLabel lbnNumberOfPeople;
    private javax.swing.JTable tblService;
    // End of variables declaration//GEN-END:variables
}
